spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:restaurant
    username: test123
    password: test123
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
